logging:
    file:
        name: GreenUniv.log
        path: /logs
    level:
        org:
            hibernate:
                orm:
                    jdbc:
                        bind: trace
        root: info
server:
    port: 8080
    servlet:
        context-path: /
spring:
    application:
        name: GreenUniv
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: Qwerty123@
        url: jdbc:mysql://3.34.46.178:3306/test_green
        username: root
    devtools:
        livereload:
            enabled: true
    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true