logging:
    file:
        name: GreenUniv.log
        path: /logs
    level:
        org:
            hibernate:
                orm:
                    jdbc:
                        bind: trace
        root: info
server:
    port: 8080
    servlet:
        context-path: /
spring:
    application:
        name: GreenUniv
<<<<<<< Updated upstream
    mail:
        host: smtp.gmail.com
        port: 587
        username: euns.lee77@gmail.com
        password: xpkh mnjy urrz okms
        properties:
            mail:
                smtp:
                    auth: true
                    timeout: 5000
                    starttls:
                        enable: true
        version: 1.0.0
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: Qwerty@123
        url: jdbc:mysql://3.34.183.157:3306/GreenUniv
=======
        version: 1.0.0
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 1234
        url: jdbc:mysql://127.0.0.1:3306/greenuniv
>>>>>>> Stashed changes
        username: root
    devtools:
        livereload:
            enabled: true
<<<<<<< Updated upstream


=======
    mail:
        host: smtp.gmail.com
        port: 587
        username: jinwooya55@gmail.com
        password: xwgi jazf lcyg uagz
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
>>>>>>> Stashed changes
    jpa:
        database: mysql
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
<<<<<<< Updated upstream
                show_sql: true

=======
                show_sql: true
>>>>>>> Stashed changes
